### PR TITLE
[cmake] Set BUILD_INTERFACE for include dirs of main ndcurves target

### PR DESCRIPTION
**Pull request by ManifoldFR**
Set BUILD_INTERFACE for include dirs of main ndcurves target, allows the project to be more easily consumed thru FetchContent

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by nim65s** [comment]
@mergifyio rebase

**Review by nim65s — APPROVED** [review]

**Comment by ManifoldFR** [comment]
Thanks @nim65s :)

**Comment by nim65s** [comment]
Thanks to you !

**Pull request merged**
