### PR TITLE
Disable python by default

### PR DESCRIPTION
**Pull request by pFernbach**
As discussed with @nim65s, required to have easier release on ferrum.

### CODE REVIEW

**Comment by stonneau** [comment]
Well I think it is really unfortunate, can we talk about this.

**Comment by pFernbach** [comment]
Sure, it will not change anything for the binaries releases on robotpkg. For everyone installing from source it just require to add `-DBUILD_PYTHON_INTERFACE=ON` in the cmake instructions (I should add that to the Readme actually). 

I need it to avoid large changes in the pipeline used to release packages on ferrum for the Talos robot. The other option is to have a fork with just this change that I use for the releases. 

Also, in term of use I think it's better to build the minimum of stuff by default and have options to build more, not less. But that's just my philosophy and so far in the packages in this namespace it seems to be the opposite used. So this is not really an argument.

**Comment by stonneau** [comment]
I m fine if the binaries stay the same. Indeed if you could output the readme for proper installation with python that d be great

**Comment by pFernbach** [comment]
Done for the Readme, thanks for the feedback.

**Pull request merged**
