### PR TITLE
add bibtex citation

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
Add a bibtex to be able to cite this work

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
up on this very simple PR?
@stonneau ?

**Comment by stonneau** [comment]
I thought we d said order was jason then pierre?

**Comment by MaximilienNaveau** [comment]
I am not sure anymore I thought it was Pierre first, but I can modify I do not have strong opinion

**Comment by stonneau** [comment]
We said we d do per number of.lines so me.Jason then Pierre then guilhem

________________________________

**Comment by MaximilienNaveau** [comment]
Done

**Pull request merged**
