### PR TITLE
Cleaned up unittest + Python command to run tests

### PR DESCRIPTION
**Pull request by cmastalli**
This PR makes the following actions:
  - Standardised test files, e.g., from "test-constant.py" to "test_constant.py". This standardisation aims to keep the same file naming style used in C++ unit tests c04909509ae5d8342d7e5cbb8b093dbe73cff679 and 2f9667ea21a659abb03ff41c80509a504b08e5fb.
  - Renamed the test folder to unitest as this is the conventional name used across many projects 75f8c5ce873d42b976cfec94be227dc35f396e30.
  - Moved Python test into the unittest folder under bindings 180ea6f37528b1cf19093fee149cf1ecbacc9cd6.
  - Created command for running Python tests c04909509ae5d8342d7e5cbb8b093dbe73cff679.

As discussed in the previous PR https://github.com/loco-3d/ndcurves/pull/104#discussion_r1280269573, we wish to change this implementation. I need time to think about the possible solutions. This is the reason why I am marking this PR as a draft.

### CODE REVIEW

**Comment by cmastalli** [comment]
Hi @nim65s -- I fixed issues with the custom command as discussed here https://github.com/loco-3d/ndcurves/pull/104#discussion_r1280757924. It is still unclear if you want me to push this into the cmake submodule. I am happy to do so if you support the idea.

**Comment by nim65s** [comment]
[If it ain't broke, don't fix it.](https://en.wikipedia.org/wiki/Wikipedia:If_it_ain%27t_broke,_don%27t_fix_it)

**Comment by cmastalli** [comment]
Hi, @nim65s -- is the entire PR useless?

Many unit tests are not passing when compiling with Clang on my MacBook. I started by cleaning up the package and creating the command to fix them later (when having time) quickly.

**Comment by nim65s** [comment]
I do not see anything useful in this PR.

The thing you are describing with clang and your mac are unrelated with the change you propose here, so please don't discuss that here, this PR is not the right place.

Also ref. https://github.com/loco-3d/ndcurves/pull/104#discussion_r1280757924

**Pull request closed without merging**
