### PR TITLE
[CMakeLists] find cppad

### PR DESCRIPTION
**Pull request by proyan**

### CODE REVIEW

**Comment by nim65s** [comment]
Do you need CppAD for this repository ? If so, shouldn't you add a `find_package` or a `add_project_dependency` ?

**Comment by proyan** [comment]
Currently we need to add this line in all downstream packages from pinocchio, if pinocchio is installed with cppad=on.

The better solution is to make this visible in jrl-cmakemodules itself. But not sure how to do that

**Comment by proyan** [comment]
I don't need cppad in this repository :)

**Comment by nim65s** [comment]
I'm not totally sure that we should add this line in all packages dependent on pinocchio (we have a lot of packages like that…), especially if we don't need this package.

I'm not sure that pinocchio should export this as a unconditionnal required dependency, even if it was compiled with its support.

We can't really make that module visible by default in the jrl-cmakemodules, the user has to be aware that it is using this component from us.

I think the best solution would be to install this file with other cmake files in pinocchio. But this require some work, and I don't have time for this right now.

If this is not too much blocking for you, I would suggest to wait for this solution to be implemented.

**Comment by proyan** [comment]
> I'm not sure that pinocchio should export this as a unconditionnal required dependency, even if it was compiled with its support.
>I'm not totally sure that we should add this line in all packages dependent on pinocchio (we have a lot of packages like that…), especially if we don't need this package.

I agree. I don't think think should be a required dependency for all downstream packages. Adding this line is just a stop-gap measure, until pinocchio or jrl-cmakeModules are updated.

I'm not sure that I understand the issue with making this visible in jrl-cmakeModules. If the user is using this macro, it _has_ to be from us, since he is consciously including `INCLUDE(cmake/base.cmake)`. Aren't all the dependency checks coming from here?

In any case, this is not blocking for me. So please feel free to merge or close this PR, or convert it to an issue.

**Comment by nim65s** [comment]
> I'm not sure that I understand the issue with making this visible in jrl-cmakeModules. If the user is using this macro, it _has_ to be from us, since he is consciously including `INCLUDE(cmake/base.cmake)`. Aren't all the dependency checks coming from here?

ref https://github.com/jrl-umi3218/jrl-cmakemodules/pull/185#issuecomment-461476215

**Comment by proyan** [comment]
Needs to be handled in jrl-cmakemodules. I'll cloee it

**Pull request closed without merging**
