### PR TITLE
Topic/piecewise generic

### PR DESCRIPTION
**Pull request by pFernbach**
Copied from https://gepgitlab.laas.fr/loco-3d/curves/merge_requests/39

Solve Issues https://gepgitlab.laas.fr/loco-3d/curves/issues/16 and https://gepgitlab.laas.fr/loco-3d/curves/issues/4

* Rework the class `piecewise_curve` to make it generic and remove the need to specify the type of curve used as a template argument, can now mix any kind of curves inside. 
* Rework the methods `convert_to_X_from_Y` to `convert_to_X` and remove the need to specify the input type as template argument.
* Add `compute_derivate_ptr()` method to `curve_abc` and implement it in all child classes.  This require to change the return type to a pointer in order to have all child class implementation return the correct type of curves. As `curve_abc` is abstract, it is not possible to use it as the return type of `compute_derivate()` .
Some of the child class did not have a `compute_derivate()` method implemented, in this case `compute_derivate_ptr()` throw and "not implemented" error.

* Add `degree()` method to `curve_abc` and implement it in all child class.
* Factorize the most commonly used typedef with template argument in fwd.h  (In order to remove them from python/python_definition, test/main and other packages depending of curves). 

## Python
* Update API to changes above
* SE3Curve and piecewise_SE3 now inherit from the same base abstract class

## Tests
* Update tests to changes of API
* Add more test cases for piecewise curves conversion
* Python : add detailed failure messages in `compareCurves()`

### CODE REVIEW

**Comment by stonneau** [comment]
I think we should leave a compute_derivate method that does not return a pointer but a copy, while adding another method that would return the requested pointer. Would that be okay ?

**Comment by pFernbach** [comment]
It does not solve the problem that compute_derivative need to return the same class than the current one. In other word the type of return need to change when the method is inherited from the base class. With inheritance it's only possible if the method return a pointer. 

There may be an other way to do this, with template for exemple, but I did not try yet and I do not see an obvious way to achieve this. 

Basically I don't need the method to return a pointer but it's the only way that I manage to make it work with the current design. All I need is a return type that match the derived class and I need to be able to call this method without knowing the exact type of the object (eg from a pointer of the base abstract class). 

If you manage to do this, you can push your changes in this PR. I will probably not have time to try to change this myself before the christmas holiday.

**Comment by stonneau** [comment]
But we need the copy return method to be inherited ?
It is only useful if you have the right instance anyways.

**Comment by pFernbach** [comment]
Ok now I understand your previous point. 
You mean that the method returning a copy (like it was done before in `bezier_curve`) is not in the base abstract class but only in some derived class, and we keep the other one returning pointer in the `curve_abc` base class with it's implementation in all the derived class but we rename it something like `compute_derivate_ptr`, right ? 

I'm ok with this and I can do it.

**Comment by stonneau** [comment]
Yes. I believe that implicitely all the classes should implement this.
This will avoid all the creation deletions in the pull request.

**Comment by pFernbach** [comment]
Done. I updated the original description of the PR.

Here is the CI : https://gepgitlab.laas.fr/pfernbac/curves/pipelines/7666

**Review by stonneau — APPROVED** [review]

**Pull request merged**
