### PR TITLE
Enabled support to copy and deepcopy

### PR DESCRIPTION
**Pull request by cmastalli**
Pickable is the worst solution for enabling an object to be copyable. Instead, the purpose solution is better while still keeping the pickability of the curves.

Additionally, the pickable solution creates segfaul in my Apple M1 chip. But, if I remember correctly, this doesn't happen in Ubuntu.

In short this PR enables us to do the following:
```python
import ndcurves
import copy

c = ndcurves.bezier()

d1 = copy.copy(c)
d2 = copy.deepcopy(c)
```

### CODE REVIEW

**Comment by cmastalli** [comment]
@stonneau and @nim65s -- this is a kind remain.

**Comment by stonneau** [comment]
Hi @cmastalli , I m not sure I understand your first comment about pickable copies. It does not seem that we made any choice regarding copies in the first place, so I m not sure I exactly understand what you suggest to replace ?

The addition of deepcopy is a nice feature though.

Only question I have regards the dependency to eigenpy 2.9. Is 2.9 available on Ubuntu 18.04 ?

Thanks

**Comment by cmastalli** [comment]
> Hi @cmastalli , I m not sure I understand your first comment about pickable copies. It does not seem that we made any choice regarding copies in the first place, so I m not sure I exactly understand what you suggest to replace ?
> 
> The addition of deepcopy is a nice feature though.
> 
> Only question I have regards the dependency to eigenpy 2.9. Is 2.9 available on Ubuntu 18.04 ?
> 
> Thanks

My understanding is that `copy` and `deepcopy` is currently using the pickeable suite already implemented. But, this is inefficient and for some reason doesn't work in my Apple M1 (this could be a local issue).

Nevertheless, this PR provides the copyable support which doesn't require to use the pickeable suite of boost python when calling `copy` and `deepcopy`. Note that we have now both supports in this PR: pickeable and copyable.

**Comment by cmastalli** [comment]
> > Hi @cmastalli , I m not sure I understand your first comment about pickable copies. It does not seem that we made any choice regarding copies in the first place, so I m not sure I exactly understand what you suggest to replace ?
> > The addition of deepcopy is a nice feature though.

> > Thanks
> 

My understanding is that `copy` and `deepcopy` is currently using the pickeable suite already implemented. But, this is inefficient and for some reason doesn't work in my Apple M1 (this could be a local issue).

Nevertheless, this PR provides the copyable support which doesn't require to use the pickeable suite of boost python when calling `copy` and `deepcopy`. Note that we have now both supports in this PR: pickeable and copyable.

**Comment by cmastalli** [comment]
> Only question I have regards the dependency to eigenpy 2.9. Is 2.9 available on Ubuntu 18.04 ?

Yes, we have. Note that the Ubuntu 18.04 job is passing: https://gitlab.laas.fr/loco-3d/ndcurves/-/jobs/193462

**Pull request merged**
